services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "vacancies_db"
      POSTGRES_USER: "vacancies_db"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data